/*  Message-number definitions derived from "ELWCHR.MSG"  */

#define LETTERS     1
#define TITLE       3
#define TGABKS      4
#define INSTR       5
#define ISFULL      6
#define CHOPTS      7
#define ANYKEY      8
#define PLSCR       9
#define ASKIMPF    10
#define IMPBAD     11
#define ABORT      12
#define MISSED     13
#define MTOOM      14
#define NEWPZL     15
#define NOMORE     16
#define CLRSCR     17
#define GTSYM      18
#define GOTW       19
#define NOTGOT     20
#define COLOR1     21
#define COLOR2     22
#define HILIST     23
#define HILINE     24
